// <auto-generated />
using BlazorCRUD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorCRUD.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("BlazorCRUD.Data.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Example Content for Post 1",
                            Title = "Post 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Example Content for Post 2",
                            Title = "Post 2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Example Content for Post 3",
                            Title = "Post 3"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Example Content for Post 4",
                            Title = "Post 4"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Example Content for Post 5",
                            Title = "Post 5"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Example Content for Post 6",
                            Title = "Post 6"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Example Content for Post 7",
                            Title = "Post 7"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Example Content for Post 8",
                            Title = "Post 8"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Example Content for Post 9",
                            Title = "Post 9"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Example Content for Post 10",
                            Title = "Post 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
